POST https://lv.blumbit.net/back/public/api/v1/auth/login
Accept: application/json
Content-Type: application/json
Authorization: Bearer 15|9fLiD2fhtC1aLgzfxCsCj888nrZWLNNDLPRoKB1E1dfa3de6

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### categorias
GET https://lv.blumbit.net/back/public/api/v1/auth/profile
Authorization: Bearer 25|APikYv3OYx76iQeqmXNT5SFWepBnEY0uYgOh16e253ec392